services:
  # Backend API service
  - type: web
    name: tickenten-api
    env: node
    region: ohio
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 30d
      - key: EMAIL_SERVICE
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        value: noreply@tickenten.com
      - key: FRONTEND_URL
        value: https://tickenten.onrender.com
      - key: MONGO_URI
        sync: false

  # Frontend service
  - type: static
    name: tickenten-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://tickenten-api.onrender.com/api 